let truthBtn = document.querySelector('.truth-btn');
let dareBtn = document.querySelector('.dare-btn');
let displaycontainer = document.querySelector('.display-container');

// Question Array
let truth = [
    "When was the last time you lied?",
    "When was the last time you cried?",
    "What's your biggest fear?",
    "Who's the last person you searched on Instagram?",
    "What's a secret you've never told anyone?",
    "Who was your first celebrity crush?",
    "Have you ever cheated in an exam?",
    "If you were going to be on a reality TV show, which would it be?",
    "What's your biggest insecurity?",
    "What's one thing you hate people knowing about you?",
    "What's your worst habit?",
    "What's the biggest misconception about you?",
    "What's one thing you wish people knew about you?",
    "Why did your last relationship break down?",
    "What's the most you've spent on a night out?",
    "Have you ever returned or re-gifted a present?",
    "Do you have a favourite sibling?",
    "What have you purchased that's been the biggest waste of money?",
    "How would you rate your looks on a scale of 1 to 10?",
    "What celebrity do you look up to?",
    "If you could be one celebrity for a day, who would it be?",
    "If you could do any job in the world, what would it be?",
    "What's your dream life?",
    "What do you value the most - money, fame, success, friends, family, etc?",
    "What’s your biggest turn off?",
    "What’s the largest age gap between you and your sexual partners?",
    "Does size really matter?",
    "Who was your worst sexual partner and why?",
    "Have you ever faked an orgasm?",
    "Have you ever been caught in action? If so, by who?",
    "If you could only ever do one position for the rest of your life, which one would it be and why?",
    "What’s the most embarrassing thing that’s happened to you during sex?",
    "Where’s the riskiest place you’ve done it?",
    "Have you ever filmed a sex tape?",
    "What’s your biggest turn on?",
    "Do you like loud or silent people in bed?",
    "What is your favourite song when it comes to action in the bedroom?",
    "What your maddest one-night stand story?",
    "Do you have a favourite sibling?",
    "What have you bought that’s been the biggest waste of money?",
    "What is a secret you have never told anyone?",
    "Do you have a hidden talent?",
    "If you could swap lives with someone in the room, who would it be?",
    "Do you have a favourite friend?",
    "Name someone you’ve pretended to like but actually couldn’t stand.",
    "If you could become invisible, what’s the worst thing you’d do?",
    "What is your most absurd dealbreaker?",
    "Have you ever broken the law?",
    "If you had to get back with an ex, who would you choose?",
    "Who would you call in the room to help bury a body?",
    "Who is the most surprising person to ever slide into your DMs?",
    "What is something you’re glad your mum doesn’t know about you?",
    "What’s the one thing you’d never do for all the money in the world?",
    "Who do you think is the worst dressed person in the room?",
    "Who in the room would be the worst person to date and why?",
    "Are second rounds exciting or exhausting?",
    "Do you fake orgasm while looking sideways or looking the person straight in the face?",
    "Do you have an “I’m getting laid tonight” outfit? What it is?",
    "Do you have any spicy pictures or videos saved on your phone?",
    "Have you ever been attracted to the same sex?",
    "Have you ever cheated/wanted to cheat?",
    "Have you ever done it in a car?",
    "Have you ever sexted anyone? If so, read one of the sexts in a fake British accent.",
    "How many people have you slept with?",
    "How often do you watch something naughty?",
    "If you got to have a threesome with people in this room, who would you do it with and why?",
    "If you were into the same sex, which celebrity would you go for?",
    "What is the most sexually adventurous thing you’d want someone to do to you?",
    "What is the most you’ve done for sex in the past?",
    "What panties are you wearing?",
    "What was the most embarrassing time you got turned on?",
    "What would be more thrilling: angry sex or make-up sex?",
    "What’s the most number of times you’ve done it in one day?",
    "What’s your favorite body part on a girl?",
    "When did you lose your virginity?",
    "When was a time you were so turned on you couldn’t stand it?",
    "When was your first kiss?",
    "When was your sexual awakening?",
    "Where are you on the straight/queer spectrum?",
    "Who do you most want to sleep with, out of everyone here?",
    "If you could make out with any one of us, who would it be?",
    "Who do you fancy the most in this room?",
];

let dare = [
    "Try to juggle 3 things of the group's choice",
    "Show the most embarrassing photo on your phone",
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Do 100 squats",
    "Let the group look in your Instagram DMs",
    "Show us your screen time report",
    "Keep three ice cubes in your mouth until they melt",
    "Yell out the first word that comes to your mind",
    "Keep your eyes closed until it's your go again",
    "Empty out your wallet/purse and show everyone what's inside",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Whisper a secret to the person on your left",
    "Say two honest things about everyone else in the group",
    "Tell the saddest story you know",
    "Hold your drink with two hands for the rest of the evening",
    "Put on make-up without a mirror and leave it like that for the rest of the game",
    "Give a lap dance to someone of your choice",
    "Seductively eat a banana",
    "Do your best sexy crawl",
    "Twerk for a minute",
    "Talk in an American accent for five minutes",
    "Do your best celebrity impression",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Down your drink (responsibly)",
    "Try and make yourself cry in front of the group",
    "Give a celebrity lookalike for every person in the room",
    "Attempt to impersonate everyone in the room",
    "Fill your mouth with drink and gargle your answer to the next Truth",
    "Attempt the first TikTok dance on your for you page",
    "Try not to laugh for the next 10 minutes",
    "Narrate the game like a newsreader for the next round",
    "Allow someone else in the group to blindfold you and feed you one item of their choice",
    "Give a foot massage to the person on your right",
    "Put as many available liquids into a cup and drink it",
    "Try and get all the toes on one foot in your mouth",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Smell another player's armpit",
    "Put your clothing on backwards for the rest of the evening",
    "Read out the last dirty text you sent",
    "Say something dirty to the person on your left",
    "Remove four items of clothing",
    "Send a sext to the last person in your phonebook",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Scroll through your phone book until someone says stop. You either have to call or delete that person.",
    "Tell the group two truths and a lie, and they have to guess which one the lie is",
    "Reply to the first five Instagram Stories on your timeline",
    "Give a personalised insult to everyone in the room",
    "Update your relationship status to 'engaged' on Facebook",
    "Call a person in the room's dad and tell him you think he's sexy",
    "Post a random baby scan on WhatsApp",
    "Comment a fire emoji on the first five pictures on your Instagram feed",
    "Let another person post a status on your behalf.",
    "Let the other players go through your phone for one minute.",
    "Let another person draw a tattoo on your back with a pen or marker.",
    "Drink a mystery drink created by the rest of the group.",
    "Show your search history on your phone.",
    "Let the rest of the group DM someone from your Instagram.",
    "Pretend to be the person on your left for 10 minutes.",
    "Whisper a secret to the person on your left.",
    "Eat something of the groups choice without using your hands.",
    "Scroll through your Instagram followers until someone says stop and you have to like all their pics.",
    "Let someone shave a part of your body.",
    "Reply to the first five Instagram stories on your timeline",
    "Send your ex a message saying you miss them.",
    "Make eye contact with the person to your right and moan for 10 seconds.",
    "Perform a seductive dance in front of the group.",
    "Pick up the nearest object to you and demonstrate how to put on condom.",
    "Google the dirtiest thing you can think of and show it to the person next to you.",
    "Smell everyone’s armpits and rank them from best to worst.",
    "Tell us the one bedtime secret no one knows about you.",
    "Exchange an item of clothing with the player on your right.",
    "Twerk along to a boring song until the music stops.",
    "Change your WhatsApp status to 'Feeling horny . . .'",
    "Change your WhatsApp status to “I’m coming . . . I’m coming . . .” Then, one minute later, change it to 'I just came.'",
    "Lay down on the ground and have someone pretend like they’re using chalk to draw an outline of your body.",
    "Let someone go through your YouTube history and read it out to the group.",
    "Lightly trace your hands over someone else’s lips and whisper “I’m coming, I’m coming,” five times.",
    "Remove one piece of clothing every time you give the wrong answer to a series of questions.",
    "Remove your bra without taking off your shirt.",
    "Someone gives you a back massage for one minutes while you’re blindfolded. If you like their style, you can choose to kiss them afterwards, but without knowing their identity.",
    "Take off the shirt of a person of your choice with only your teeth.",
    "You get to dress up a person of your choice, using your clothes. Then take a picture.",
    "You have to keep your hand on the very inner thigh of the person next to you for the next round.",
    "You leave the room. Everyone pours a shot. You come back into the room and take one of the shots that was poured. Whoever poured the drink, you have to sit on their lap for the rest of the cycle.",
    "Show the group the last adult film you watched – no cheating!",
    "Pick a person and give them a kiss on their favorite body part.",
    "Sit right beside person to your right and lean in like you are going to kiss. Instead, hold and wait. First one to go for the kiss loses.",
    "Show me some old intimate photos of yourself that I’ve never seen.",
    "Undress someone without using your hands",
    "Give someone a kiss and pass a gum or a candy as you do.",
];

truthBtn.addEventListener('click', () => {
    let trueValue = truth[Math.floor(Math.random() * truth.length)];
    displaycontainer.innerHTML = `<p class='text'> ${trueValue}</p>`;
})

dareBtn.addEventListener('click', () => {
    let dareValue = dare[Math.floor(Math.random() * dare.length)];
    displaycontainer.innerHTML = `<p class='text'> ${dareValue}</p>`;
})